apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 3
  template:
    spec:
      containers:
      - env:
        - name: ARGOCD_API_SERVER_REPLICAS
          value: '3'
        name: argocd-server
