apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  replicas: 3
  template:
    spec:
      containers:
      - env:
        - name: ARGOCD_CONTROLLER_REPLICAS
          value: "3"
        name: argocd-application-controller
